name: remote ssh command
on: [push]
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh comands using key
      uses: appleboy/ssh-action@master
      with: 
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.KEY}}
        port: ${{secrets.PORT}}
        script: |
          ../../deploy.sh
